"""AI-powered report generation for scan results using LLM analysis."""

import json
import os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class AiReport:
    """Structured report generated by AI analysis of scan results."""

    summary: str
    """One-paragraph summary of findings."""

    risk_assessment: str
    """Risk level and explanation (low / medium / high)."""

    platform_highlights: List[str]
    """Key platforms where the username was found."""

    correlations: List[str]
    """Cross-platform correlations discovered."""

    recommendations: List[str]
    """Actionable recommendations."""

    raw_output: str = ""
    """Raw LLM response text."""


class AiReporter:
    """Uses LLM (OpenAI-compatible API) to analyze and summarize scan results.

    Provides both high-level analysis and structured reports from raw
    CheckResult data. Falls back gracefully if no API key is configured.

    Usage::

        reporter = AiReporter(api_key="sk-...", model="gpt-4")
        report = await reporter.analyze(check_results, correlations)
        print(report.summary)
    """

    DEFAULT_MODEL = "gpt-4o-mini"
    DEFAULT_API_BASE = "https://api.openai.com/v1"

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        api_base: Optional[str] = None,
        temperature: float = 0.3,
    ) -> None:
        self._api_key = api_key or os.environ.get("OPENAI_API_KEY", "")
        self._model = model or os.environ.get("OPENAI_MODEL", self.DEFAULT_MODEL)
        self._api_base = api_base or os.environ.get(
            "OPENAI_API_BASE", self.DEFAULT_API_BASE
        )
        self._temperature = temperature
        self._available = bool(self._api_key)

    @property
    def available(self) -> bool:
        """Whether an API key is configured and AI analysis can run."""
        return self._available

    async def analyze(
        self,
        results: List[Dict[str, Any]],
        correlations: Optional[List[Dict[str, Any]]] = None,
        username: str = "",
    ) -> AiReport:
        """Run AI analysis on scan results.

        Args:
            results: List of check result dicts (serialized CheckResult).
            correlations: Optional list of correlation result dicts.
            username: The username that was scanned.

        Returns:
            AiReport with summary, risk assessment, and recommendations.
        """
        if not self._available:
            return self._fallback_report(results, username)

        prompt = self._build_prompt(results, correlations, username)

        try:
            import httpx

            async with httpx.AsyncClient(timeout=60) as client:
                resp = await client.post(
                    f"{self._api_base}/chat/completions",
                    headers={
                        "Authorization": f"Bearer {self._api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "model": self._model,
                        "messages": [
                            {
                                "role": "system",
                                "content": (
                                    "You are an OSINT analysis assistant. "
                                    "Analyze the following username scan results "
                                    "and produce a concise intelligence summary."
                                ),
                            },
                            {"role": "user", "content": prompt},
                        ],
                        "temperature": self._temperature,
                    },
                )
                resp.raise_for_status()
                data = resp.json()
                content = data["choices"][0]["message"]["content"]
        except Exception as exc:
            return AiReport(
                summary=f"AI analysis failed: {exc}",
                risk_assessment="unknown",
                platform_highlights=[],
                correlations=[],
                recommendations=[],
                raw_output=str(exc),
            )

        return self._parse_response(content, results, username)

    def _build_prompt(
        self,
        results: List[Dict[str, Any]],
        correlations: Optional[List[Dict[str, Any]]],
        username: str,
    ) -> str:
        """Build the LLM prompt from scan results."""
        found = [r for r in results if r.get("status") == "found"]
        not_found = [r for r in results if r.get("status") == "not_found"]
        errors = [r for r in results if r.get("status") == "error"]

        lines = [
            f"Username scanned: {username}",
            f"Total platforms checked: {len(results)}",
            f"Profiles found: {len(found)}",
            f"Not found: {len(not_found)}",
            f"Errors: {len(errors)}",
            "",
            "=== FOUND PLATFORMS ===",
        ]
        for r in found:
            data = r.get("data") or {}
            lines.append(
                f"- {r['platform']}: {data.get('name', 'N/A')} | "
                f"bio: {data.get('bio', 'N/A')[:100]} | "
                f"location: {data.get('location', 'N/A')} | "
                f"url: {data.get('url', 'N/A')}"
            )

        if correlations:
            lines.extend(["", "=== CORRELATIONS ==="])
            for c in correlations:
                lines.append(
                    f"- Platforms: {', '.join(c.get('platforms', []))} | "
                    f"confidence: {c.get('confidence', 0)} | "
                    f"matched by: {', '.join(c.get('matched_by', []))}"
                )

        lines.extend([
            "",
            "Please provide:",
            "1. A one-paragraph summary of findings",
            "2. A risk assessment (low/medium/high) with reasoning",
            "3. Key platform highlights",
            "4. Notable cross-platform correlations",
            "5. Actionable recommendations",
        ])

        return "\n".join(lines)

    def _parse_response(
        self,
        content: str,
        results: List[Dict[str, Any]],
        username: str,
    ) -> AiReport:
        """Parse LLM response into a structured AiReport."""
        found_platforms = [
            r["platform"]
            for r in results
            if r.get("status") == "found"
        ]
        return AiReport(
            summary=content[:500] if len(content) > 500 else content,
            risk_assessment=self._extract_risk(content),
            platform_highlights=found_platforms[:10],
            correlations=[],
            recommendations=self._extract_recommendations(content),
            raw_output=content,
        )

    @staticmethod
    def _extract_risk(content: str) -> str:
        """Extract risk level from LLM response."""
        content_lower = content.lower()
        if "high" in content_lower:
            return "high"
        elif "medium" in content_lower:
            return "medium"
        return "low"

    @staticmethod
    def _extract_recommendations(content: str) -> List[str]:
        """Extract bullet-point recommendations from LLM response."""
        recs = []
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("- ") or line.startswith("* "):
                recs.append(line[2:].strip())
            elif line.startswith("1.") or line.startswith("2.") or line.startswith("3."):
                parts = line.split(".", 1)
                if len(parts) == 2:
                    recs.append(parts[1].strip())
        return recs[:10]

    @staticmethod
    def _fallback_report(
        results: List[Dict[str, Any]],
        username: str,
    ) -> AiReport:
        """Generate a basic report without AI."""
        found = [r for r in results if r.get("status") == "found"]
        found_names = [r["platform"] for r in found]
        if found:
            summary = (
                f"Username '{username}' was found on "
                f"{len(found)} platform(s): {', '.join(found_names[:10])}"
                f"{' and more' if len(found_names) > 10 else ''}."
            )
        else:
            summary = (
                f"Username '{username}' was not found on any "
                f"of the {len(results)} platforms checked."
            )
        return AiReport(
            summary=summary,
            risk_assessment="medium" if len(found) > 5 else "low",
            platform_highlights=found_names[:10],
            correlations=[],
            recommendations=[
                "Set OPENAI_API_KEY environment variable for AI-powered analysis.",
                "Review the detailed results table for platform-specific data.",
            ],
        )
